name: agv-ml
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - torchvision
      - pandas
      - numpy
      - matplotlib
      - scikit-learn
      - tqdm
      - openpyxl
      - pygame
      - imageio
      - imageio-ffmpeg
